title: Oh, Hai! This is v0idkr4fts github.io page
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: v0idkr4ft #if your site has a twitter account, enter it here

# Author Settings
author: v0idkr4ft # add your name
author-img: facemlt.gif # add your photo
about-author: Time is moving faster now. # add description
social-twitter: v0idkr4ft # add your Twitter handle
social-reddit: v0idkr4ft # add your Facebook handle
social-github: v0idkr4ft # add your Github handle
social-instagram: v0idkr4ft # add your Linkedin handle
social-email: sage@v0idkr4ft.com # add your Email address

# Disqus
discus-identifier: v0idkr4ft  # add your discus identifier

# Tracker
analytics: UA-154951018-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"


exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

#server setttings
port: 4001
