title: ꧁ⅴØɨᖙʞr4ʄߙ꧂
description: > # this means to ignore newlines until "baseurl:"
  v0idkr4ft@nexus - ₴̦͕̼͎̹͔͔̱̰̑̒͛̋ͨͭ̽ͥ₱̬̬̌ͅł̫̰͉̅̍̀Ɽ̝̠͉͎͓̥͙̯̬̅̑ͭ͌̔ͣ₳̟͖͒̉Ⱡ̜̝̥̻͆̊̌͋͑ ̝̯̳͎͈̞̣̪ͯ̈̋&̣̯̤̙̦̦̔̋̍ͣ̈́͆ ̤̬̭̿̑ͭͩ̿₣̣̠͎̠̪̲͎̂ͬ̽͋̾̃Ⱡ̪̻̋̌̎̈́ͦͧ͑Ʉ̮͚̼ͫͯ̈͂̍ͫ̉̓̉ͅӾ̀̓ͪͤ͛ͦ
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: https://v0idkr4ft.com # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: v0idkr4ft #if your site has a twitter account, enter it here

# Author Settings
author: ꧁ⅴØɨᖙʞr4ʄߙ꧂ # add your name
author-img: facemlt.gif # add your photo
about-author: Time is moving faster now. # add description
custom-link: https://v0idkr4ft.com
custom-text: ₴̑₱̌ł̅Ɽ̅₳Ⱡ &̔ ₣̂Ⱡ̋ɄӾ
social-twitter: v0idkr4ft # add your Twitter handle
social-reddit: v0idkr4ft # add your Reddit handle
social-github: v0idkr4ft # add your Github handle
social-instagram: v0idkr4ft # add your Instagram handle
social-email: kalieris@v0idkr4ft.com # add your Email address

# Disqus
discus-identifier: v0idkr4ft  # add your discus identifier

# Tracker
# analytics: UA-154951018-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"


exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

#server setttings
port: 4001
